<?php

namespace App\Exports;

use App\Models\SamaProductsModel;
use App\Models\SamaProductGemstoneDetails;
use Maatwebsite\Excel\Concerns\FromCollection;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Support\Collection;
use Illuminate\Support\Facades\Schema;
use Maatwebsite\Excel\Concerns\WithHeadings;
use Maatwebsite\Excel\Concerns\FromQuery;
use Illuminate\Support\Facades\DB;

class SamaProducts implements FromQuery, WithHeadings
{
    public function query()
    {
        // return SamaProductsModel::query()
        //     ->select([
        //         'sama_products.*',
        //         'sama_product_gemstones.*',
        //     ])
        //

        return SamaProductsModel::query()
            ->select([
                'sama_products.id',
                'sama_products.sku',
                'sama_products.on_parent_sku',
                // 'products.internal_sku',
                DB::raw("CONCAT('SA', sama_products.on_parent_sku) AS prefixed_parent_sku"),
                DB::raw(
                    '
                    REPLACE(REPLACE(REPLACE(COALESCE(sama_products.fractionsemimount, "0"), " ct", ""), " tw", ""), "/", "") AS formatted_fraction'
                ),
                'sama_products.sama_parent_sku as internal_sku_copy',
                'sama_products.fractionsemimount',
                DB::raw(
                    '
                    CASE
                        WHEN sama_products.fractionsemimount LIKE "%/%"
                        THEN CAST(SUBSTRING_INDEX(sama_products.fractionsemimount, " ", 1) AS UNSIGNED) /
                             NULLIF(CAST(SUBSTRING_INDEX(SUBSTRING_INDEX(sama_products.fractionsemimount, "/", -1), " ", 1) AS UNSIGNED), 0)
                        ELSE 0
                    END AS decimal_value'
                ),
                'sama_products.metalType',
                'sama_products.metalColor',
                'sama_products.diamondQuality',
                'sama_products.CenterShape',
                'sama_products.SideDiamondNumber',
                'sama_products.SideDiamondNumber_Min',
                'sama_products.SideDiamondNumber_Max',
                'sama_products.TotalDiamondWeight',
                'sama_products.metalWeight',
                'sama_products.metalWeight_Min',
                'sama_products.metalWeight_Max',
                'sama_product_gemstones.GemstoneShape1',
                'sama_product_gemstones.NoOfGemstones1',
                'sama_product_gemstones.NoOfGemstones1_Min',
                'sama_product_gemstones.NoOfGemstones1_Max',
                'sama_product_gemstones.GemstoneLotCode1',
                'sama_product_gemstones.GemstoneWeight1',
                'sama_product_gemstones.GemstoneWeight1_Min',
                'sama_product_gemstones.GemstoneWeight1_Max',
                'sama_product_gemstones.GemstoneShape2',
                'sama_product_gemstones.NoOfGemstones2',
                'sama_product_gemstones.NoOfGemstones2_Min',
                'sama_product_gemstones.NoOfGemstones2_Max',
                'sama_product_gemstones.GemstoneLotCode2',
                'sama_product_gemstones.GemstoneWeight2',
                'sama_product_gemstones.GemstoneWeight2_Min',
                'sama_product_gemstones.GemstoneWeight2_Max',
                'sama_product_gemstones.GemstoneShape3',
                'sama_product_gemstones.NoOfGemstones3',
                'sama_product_gemstones.NoOfGemstones3_Min',
                'sama_product_gemstones.NoOfGemstones3_Max',
                'sama_product_gemstones.GemstoneLotCode3',
                'sama_product_gemstones.GemstoneWeight3',
                'sama_product_gemstones.GemstoneWeight3_Min',
                'sama_product_gemstones.GemstoneWeight3_Max',
                'sama_product_gemstones.GemstoneShape4',
                'sama_product_gemstones.NoOfGemstones4',
                'sama_product_gemstones.NoOfGemstones4_Min',
                'sama_product_gemstones.NoOfGemstones4_Max',
                'sama_product_gemstones.GemstoneLotCode4',
                'sama_product_gemstones.GemstoneWeight4',
                'sama_product_gemstones.GemstoneWeight4_Min',
                'sama_product_gemstones.GemstoneWeight4_Max',
                'sama_product_gemstones.GemstoneShape5',
                'sama_product_gemstones.NoOfGemstones5',
                'sama_product_gemstones.NoOfGemstones5_Min',
                'sama_product_gemstones.NoOfGemstones5_Max',
                'sama_product_gemstones.GemstoneLotCode5',
                'sama_product_gemstones.GemstoneWeight5',
                'sama_product_gemstones.GemstoneWeight5_Min',
                'sama_product_gemstones.GemstoneWeight5_Max',
                'sama_product_gemstones.GemstoneShape6',
                'sama_product_gemstones.NoOfGemstones6',
                'sama_product_gemstones.NoOfGemstones6_Min',
                'sama_product_gemstones.NoOfGemstones6_Max',
                'sama_product_gemstones.GemstoneLotCode6',
                'sama_product_gemstones.GemstoneWeight6',
                'sama_product_gemstones.GemstoneWeight6_Min',
                'sama_product_gemstones.GemstoneWeight6_Max',
                'sama_product_gemstones.GemstoneShape7',
                'sama_product_gemstones.NoOfGemstones7',
                'sama_product_gemstones.NoOfGemstones7_Min',
                'sama_product_gemstones.NoOfGemstones7_Max',
                'sama_product_gemstones.GemstoneLotCode7',
                'sama_product_gemstones.GemstoneWeight7',
                'sama_product_gemstones.GemstoneWeight7_Min',
                'sama_product_gemstones.GemstoneWeight7_Max',
                'sama_product_gemstones.GemstoneShape8',
                'sama_product_gemstones.NoOfGemstones8',
                'sama_product_gemstones.NoOfGemstones8_Min',
                'sama_product_gemstones.NoOfGemstones8_Max',
                'sama_product_gemstones.GemstoneLotCode8',
                'sama_product_gemstones.GemstoneWeight8',
                'sama_product_gemstones.GemstoneWeight8_Min',
                'sama_product_gemstones.GemstoneWeight8_Max',
                'sama_product_gemstones.GemstoneShape9',
                'sama_product_gemstones.NoOfGemstones9',
                'sama_product_gemstones.NoOfGemstones9_Min',
                'sama_product_gemstones.NoOfGemstones9_Max',
                'sama_product_gemstones.GemstoneLotCode9',
                'sama_product_gemstones.GemstoneWeight9',
                'sama_product_gemstones.GemstoneWeight9_Min',
                'sama_product_gemstones.GemstoneWeight9_Max',
                'sama_product_gemstones.GemstoneShape10',
                'sama_product_gemstones.NoOfGemstones10',
                'sama_product_gemstones.NoOfGemstones10_Min',
                'sama_product_gemstones.NoOfGemstones10_Max',
                'sama_product_gemstones.GemstoneLotCode10',
                'sama_product_gemstones.GemstoneWeight10',
                'sama_product_gemstones.GemstoneWeight10_Min',
                'sama_product_gemstones.GemstoneWeight10_Max',
                'sama_products.FingerSize',
                'sama_products.bandwidth',
                'sama_products.bandweight',
                'sama_products.category',
                'sama_products.subcategory',
                'sama_products.product_browse_pg_name',
                'sama_products.product_pg_name',
                'sama_products.description',
                'sama_products.center_stone_options',
                'sama_products.matching_wedding_band',
                'sama_products.product',
                // 'sama_products.default_image_url',
                'sama_products.images',
                'sama_products.videos',
            ])
            ->join('sama_product_gemstones', 'sama_product_gemstones.product_id', '=', 'sama_products.id');
    }

    public function headings(): array
    {
        return $columns = [
            'num',
            'SAMA INTERNAL PRICE REF',
            'ON PARENT SKU',
            'SAMA PARENT SKU',
            'SAMA CHILD SKU',
            'SAMA SKU',
            'fractionsemimount',
            'fractionsemimount_value',
            'metaltype',
            'metalcolor',
            'diamondQuality',
            'CenterShape',
            'SideDiamondNumber',
            'SideDiamondNumber_Min',
            'SideDiamondNumber_Max',
            'TotalDiamondWeight',
            'metalWeight',
            'metalWeight_Min',
            'metalWeight_Max',
            'GemstoneShape1',
            'NoOfGemstones1',
            'NoOfGemstones1_Min',
            'NoOfGemstones1_Max',
            'GemstoneLotCode1',
            'GemstoneWeight1',
            'GemstoneWeight1_Min',
            'GemstoneWeight1_Max',
            'GemstoneShape2',
            'NoOfGemstones2',
            'NoOfGemstones2_Min',
            'NoOfGemstones2_Max',
            'GemstoneLotCode2',
            'GemstoneWeight2',
            'GemstoneWeight2_Min',
            'GemstoneWeight2_Max',
            'GemstoneShape3',
            'NoOfGemstones3',
            'NoOfGemstones3_Min',
            'NoOfGemstones3_Max',
            'GemstoneLotCode3',
            'GemstoneWeight3',
            'GemstoneWeight3_Min',
            'GemstoneWeight3_Max',
            'GemstoneShape4',
            'NoOfGemstones4',
            'NoOfGemstones4_Min',
            'NoOfGemstones4_Max',
            'GemstoneLotCode4',
            'GemstoneWeight4',
            'GemstoneWeight4_Min',
            'GemstoneWeight4_Max',
            'GemstoneShape5',
            'NoOfGemstones5',
            'NoOfGemstones5_Min',
            'NoOfGemstones5_Max',
            'GemstoneLotCode5',
            'GemstoneWeight5',
            'GemstoneWeight5_Min',
            'GemstoneWeight5_Max',
            'GemstoneShape6',
            'NoOfGemstones6',
            'NoOfGemstones6_Min',
            'NoOfGemstones6_Max',
            'GemstoneLotCode6',
            'GemstoneWeight6',
            'GemstoneWeight6_Min',
            'GemstoneWeight6_Max',
            'GemstoneShape7',
            'NoOfGemstones7',
            'NoOfGemstones7_Min',
            'NoOfGemstones7_Max',
            'GemstoneLotCode7',
            'GemstoneWeight7',
            'GemstoneWeight7_Min',
            'GemstoneWeight7_Max',
            'GemstoneShape8',
            'NoOfGemstones8',
            'NoOfGemstones8_Min',
            'NoOfGemstones8_Max',
            'GemstoneLotCode8',
            'GemstoneWeight8',
            'GemstoneWeight8_Min',
            'GemstoneWeight8_Max',
            'GemstoneShape9',
            'NoOfGemstones9',
            'NoOfGemstones9_Min',
            'NoOfGemstones9_Max',
            'GemstoneLotCode9',
            'GemstoneWeight9',
            'GemstoneWeight9_Min',
            'GemstoneWeight9_Max',
            'GemstoneShape10',
            'NoOfGemstones10',
            'NoOfGemstones10_Min',
            'NoOfGemstones10_Max',
            'GemstoneLotCode10',
            'GemstoneWeight10',
            'GemstoneWeight10_Min',
            'GemstoneWeight10_Max',
            'FingerSize',
            'bandwidth (mm)',
            'bandweight',
            'CATEGORY',
            'SUBCATEGORY',
            'PRODUCT BROWSE PG NAME',
            'PRODUCT PG NAME',
            'DESCRIPTION',
            'CENTER STONE OPTIONS',
            'MATCHING WEDDING BAND',
            'PRODUCT',
            // 'default_image_url',
            'images',
            'videos',
        ];
    }
}
